### ISSUE TITLE
Maybe need a Readme?

### ISSUE THREAD

**Issue by 05bmckay** [mattchesters/zmk-apple-desktop-bus-keyboard#1]
Hey Matt, really loved the video, do you think we could get a build guide?

**Comment by blairjj** [comment]
I agree with this 100%...  Just bought my keyboard and am ready to move forward!  Happy to help with the guide!

**Comment by 05bmckay** [comment]
@blairjj do you want to do a build guide with me? I also have my keyboard and all the part ready to roll.

**Comment by mattchesters** [comment]
more than happy for someone else to tackle this as I might not be able to make a start until next week.

**Comment by d-n-l-lab** [comment]
Same here, I am stuck at the moment - what an awesome project

**Comment by blairjj** [comment]
I am cleaning my keyboard now and am ready to start buying parts and getting going!  I can start printing the new plastic parts soon.

**Comment by mattchesters** [comment]
I have created a basic README, however I will accept contributions if you feel it is missing anything ☺️ Hopefully it's a good enough start!
